(function () {"use strict";
ideaPress.importModulesAndSetOptions( 
['/modules/wordpress/js/wp.module.js', '/modules/wordpressCom/js/wpcom.module.js'],
function() {
ideaPress.options = {                            
appTitleImage: null,                      // App title image
appTitle: "The LazyBlogger",                  // App title text 
cacheTime: 3600000,                       // Global cache time to try fetch
mainUrl: 'sumitmaitra.wordpress.com',         // Main promoting site
privacyUrl: 'http://sumitmaitra.wordpress.com/privacy',      // Privacy URL 
modules: [                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: 'Pages', typeId: wordpresscomModule.PAGES, pageIds: [481,2], clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: 'Recent News', typeId: wordpresscomModule.MOSTRECENT, clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: 'Bookmark', typeId: wordpresscomModule.BOOKMARKS, clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "OS", typeId: wordpresscomModule.CATEGORY, categoryId: 'os', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Quickbytes", typeId: wordpresscomModule.CATEGORY, categoryId: 'quickbytes', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Windows 8 RT", typeId: wordpresscomModule.CATEGORY, categoryId: 'windows-8-rt', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Big Data", typeId: wordpresscomModule.CATEGORY, categoryId: 'big-data', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Bing", typeId: wordpresscomModule.CATEGORY, categoryId: 'bing', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Google", typeId: wordpresscomModule.CATEGORY, categoryId: 'google', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Search Engine", typeId: wordpresscomModule.CATEGORY, categoryId: 'search-engine', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Craft Projects", typeId: wordpresscomModule.CATEGORY, categoryId: 'craft-projects', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Parenting", typeId: wordpresscomModule.CATEGORY, categoryId: 'parenting', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Personal", typeId: wordpresscomModule.CATEGORY, categoryId: 'personal', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Office 2013", typeId: wordpresscomModule.CATEGORY, categoryId: 'office-2013', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Surface RT", typeId: wordpresscomModule.CATEGORY, categoryId: 'surface-rt', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Gadgets", typeId: wordpresscomModule.CATEGORY, categoryId: 'gadgets', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Surface Pro", typeId: wordpresscomModule.CATEGORY, categoryId: 'surface-pro', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Politics", typeId: wordpresscomModule.CATEGORY, categoryId: 'politics', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Social Responsibilities", typeId: wordpresscomModule.CATEGORY, categoryId: 'social-responsibilities', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Uncategorized", typeId: wordpresscomModule.CATEGORY, categoryId: 'uncategorized', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Mobile Services", typeId: wordpresscomModule.CATEGORY, categoryId: 'mobile-services', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Blogging", typeId: wordpresscomModule.CATEGORY, categoryId: 'blogging', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "OSX (Snow Leopard)", typeId: wordpresscomModule.CATEGORY, categoryId: 'osx-snow-leopard', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Windows 7", typeId: wordpresscomModule.CATEGORY, categoryId: 'windows-7', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "ASP.NET", typeId: wordpresscomModule.CATEGORY, categoryId: 'asp-net', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "MVC", typeId: wordpresscomModule.CATEGORY, categoryId: 'mvc', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Visual Studio", typeId: wordpresscomModule.CATEGORY, categoryId: 'visual-studio', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Project Management", typeId: wordpresscomModule.CATEGORY, categoryId: 'project-management', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Entity Framework", typeId: wordpresscomModule.CATEGORY, categoryId: 'entity-framework', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "SignalR", typeId: wordpresscomModule.CATEGORY, categoryId: 'signalr', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Cocoa", typeId: wordpresscomModule.CATEGORY, categoryId: 'cocoa', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "iOS", typeId: wordpresscomModule.CATEGORY, categoryId: 'ios', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Objective C", typeId: wordpresscomModule.CATEGORY, categoryId: 'objective-c', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Programming", typeId: wordpresscomModule.CATEGORY, categoryId: 'programming', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "C#", typeId: wordpresscomModule.CATEGORY, categoryId: 'c', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Mac Book Pro", typeId: wordpresscomModule.CATEGORY, categoryId: 'mac-book-pro', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Sharepoint", typeId: wordpresscomModule.CATEGORY, categoryId: 'sharepoint', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "SQL Server", typeId: wordpresscomModule.CATEGORY, categoryId: 'sql-server', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Entertainment", typeId: wordpresscomModule.CATEGORY, categoryId: 'entertainment', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Movies", typeId: wordpresscomModule.CATEGORY, categoryId: 'movies', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Chrome OS", typeId: wordpresscomModule.CATEGORY, categoryId: 'chrome-os', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "iPhone", typeId: wordpresscomModule.CATEGORY, categoryId: 'iphone', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "iPhone ownership experience", typeId: wordpresscomModule.CATEGORY, categoryId: 'iphone-ownership-experience', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } },
                { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: "Football", typeId: wordpresscomModule.CATEGORY, categoryId: 'football', clientId: '2719', clientSecret: ' 	FdxzsHMCdAcB13ED9j5Y2oyROyJKf0KzvpUQ86Bw8r5IiedvedmjNuMRW7fKc9wk ' } }],
searchModule: { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: 'Search' } }, 
liveTileModule: { name: wordpresscomModule, options: { siteDomain: 'sumitmaitra.wordpress.com', title: 'Live', squareTileType: Windows.UI.Notifications.TileTemplateType.tileSquarePeekImageAndText04, wideTileType : Windows.UI.Notifications.TileTemplateType.tileWideImageAndText01 } } 
};
});
})();

